djangotutorial/accounts/urls.py
from django.urls import re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^signup/$', views.signup_view, name='signup'),
    re_path(r'^login/$', views.login_view, name='login'),
    re_path(r'^logout/$', views.logout_view, name='logout'),
]

djangotutorial/articles/urls.py
from django.urls import re_path
from . import views

app_name = 'articles'

urlpatterns = [
    re_path(r'^$', views.article_list, name='list'),
    re_path(r'^create/$', views.article_create, name='create'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='details'),
]

djangotutorial/djangotutorial/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^articles/', include('articles.urls')),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^about/$',views.about),
    re_path(r'^$', article_views.article_list, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangotutorial/accounts/models.py
from django.db import models

# Create your models here.

djangotutorial/articles/models.py
from django import forms
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[:50] + '...'

djangotutorial/articles/forms.py
from django import forms
from .import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

djangotutorial/accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if (request.method == 'POST'):
        form = UserCreationForm(request.POST)
        if (form.is_valid()):
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {
        'form': form
    })

def login_view(request):
    if (request.method == 'POST'):
        form = AuthenticationForm(data=request.POST)
        if (form.is_valid()):
            user = form.get_user()
            login(request, user)
            if ('next' in request.POST):
                return redirect(request.POST.get('next'))
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {
        'form': form
    })

def logout_view(request):
    if (request.method == 'POST'):
        logout(request)
        return redirect ('articles:list')

djangotutorial/articles/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/index.html', {
        'articles':articles
    })

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/show.html', {
        'article': article
    })

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            #save article to db
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/create.html', {'form': form})

djangotutorial/djangotutorial/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')
    # return HttpResponse('Home Page')

def about(request):
    return render(request, 'about.html')
    # return HttpResponse('about')

djangotutorial/accounts/templates/accounts/login.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Log In</h1>
    <form action="{% url 'accounts:login' %}" class="site-form" method='POST'>
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock content %}

djangotutorial/accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Sign up</h1>
    <form action="{% url 'accounts:signup' %}" class="site-form" method='POST'>
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock content %}

djangotutorial/articles/templates/articles/create.html
{% extends 'layout.html' %}


{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form action="{% url 'articles:create' %}" class="site-form" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}
    

djangotutorial/articles/templates/articles/index.html
{% extends 'layout.html' %} 

{% block content %}
  <h1>Article List</h1>
  <div class="articles">
    {% for article in articles %}
    <div class="article">
      <h2><a href="{% url 'articles:details' slug=article.slug %}">{{ article.title }}</a></h2>
      <p>{{ article.snippet }}</p>
      <p>{{ article.date }}</p>
    </div>
    {% endfor %}
  </div>
{% endblock %}

djangotutorial/articles/templates/articles/show.html
{% extends 'layout.html' %}

{% block content %}
    <div class="article-details">
        <div class="article">
            <img height="300px" width="500px" src="{{ article.thumb.url }}">
            <h2>{{ article.title }}</h2>
            <p>{{ article.body }}</p>
            <p>{{ article.date }}</p>
        </div>
    </div>
{% endblock content %}

djangotutorial/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>About us</h1>
    <p>We like django</p>
</body>
</html>

djangotutorial/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
    <h1>This is the home page</h1>
    <p>Welcome to django tutorial</p>
</body>
</html>

djangotutorial/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
    <title>Articles</title>
  </head>
  <body>
    <header class="wrapper">
      <h1>
        <a href="{% url 'home' %}"
          ><img src="{% static 'logo.png' %}"
        /></a>
      </h1>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <form
              class="logout-link"
              action="{% url 'accounts:logout' %}"
              method="post"
            >
              {% csrf_token %}
              <button type="submit">Logout</button>
            </form>
          </li>
          <li><a href="{% url 'articles:create' %}" class="highlight">Create Article</a></li>
          {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <div class="wrapper">{% block content %} {% endblock %}</div>
  </body>
</html>